### ISSUE TITLE
LifeCam vs. Raspberry Pi Camera v2

### ISSUE THREAD

**Issue by jaydeflix** [MicrosoftEdge/magic-mirror-demo#26]
Since we're using the Cognitive Services Face API to recognize the face and not Hello (don't even know if the life cam supports hello), anyone think the RP camera might be usable through the mirror so as to avoid the kibble sticking out visibly?

**Comment by seksenov** [comment]
The camera sticking out would definitely be a design improvement. We wanted to integrate the camera in the bezel but were short on time for //BUILD. Our thought was to take the LifeCam apart and make a hole in the mirror frame that it would fit into.

Hello isn't supported on the Pi itself it requires a few missing components / more power on the device. If you are referring to this RP [camera module](https://www.raspberrypi.org/products/camera-module/) it's currently not supported by Windows IoT. [Here ](https://developer.microsoft.com/en-us/windows/iot/win10/SupportedInterfaces.htm)is the full list of supported devices if you'd like to check it out.

**Comment by jaydeflix** [comment]
> If you are referring to this RP camera module it's currently not supported by Windows IoT.

D'oh! Hadn't even considered that possibility. Curses, so much for easily cutting it down. At least the LifeCAm is small. Might find a way to try it internal. Thanks!

**Comment by seksenov** [comment]
Send a pick or two if you do make it internal. That'll look slick.

**Comment by jaydeflix** [comment]
Will do.
