### ISSUE TITLE
Create Profile - 2nd page

### ISSUE THREAD

**Issue by RyanSepio** [MicrosoftEdge/magic-mirror-demo#31]
When I run the build for http://webreflections.azurewebsites.net/create

The Set up runs but I cannot advance to the 2nd page.  Hitting next does nothing.

Any ideas?

**Comment by sldghmmr** [comment]
Same for me.  Running Windows 10, Visual Studio 2015, and have a Logitech HD Pro C920 webcam.

**Comment by RyanSepio** [comment]
Anyone?

**Comment by sldghmmr** [comment]
Any solution yet?

**Comment by andypavia** [comment]
Updating the NPM version on the server did the trick.

**Comment by sldghmmr** [comment]
Thank you soooo much
