### ISSUE TITLE
Frustrated

### ISSUE THREAD

**Issue by rudymcdaniel23608** [MicrosoftEdge/magic-mirror-demo#35]
I've tried everything I know to get this to work.  I cannot get past the CREATE phase.  I hangs there with a big X BOX on the screen.  I would appreciate any help I could get.  Thanks!

**Comment by sldghmmr** [comment]
I was able to get past this problem by completing step three of the second part: 

Within the package.appxmanifest view, click the Content URIs tab and insert http://webreflections.azurewebsites.net/ with WinRT Access All****

After that, me and another guy had a problem getting to the second page for the facial recognition.  We have a post (Create Profile - 2nd page) on the Issues tab.  Please add your comments if you have the same problem.  Good luck.  
I you **don't** have a problem, let us know too.  Thanks

**Comment by rudymcdaniel23608** [comment]
Thanks, that got me to page 1 but still no page 2.

**Comment by sldghmmr** [comment]
Any solutions yet?

**Comment by andypavia** [comment]
Problem resolved! See https://github.com/MicrosoftEdge/magic-mirror-demo/issues/31#issuecomment-229234903
