### ISSUE TITLE
US Only - Again?!

### ISSUE THREAD

**Issue by pauliolio** [MicrosoftEdge/magic-mirror-demo#36]
Seriously?!

I'm in the UK, we don't have ZIP codes, we have Postcodes.
It really is annoying the way big American developers ignore the rest of the world.
(Anyone tried getting an Echo to work outside of the U.S.?)

**Comment by jdalton** [comment]
Hi @pauliolio!

We're a small PM team releasing this demo to show what's possible. There's plenty of room for polish for sure. If you'd like to build-on or expand the demo that would be great!
