### ISSUE TITLE
Uhhhhhhhh no

### ISSUE THREAD

**Issue by cowboysdude** [MicrosoftEdge/magic-mirror-demo#45]
Why would i want to send my image over the web to have my mirror turn on?  That's just not smart... sorry not happening.

**Comment by melanierichards** [comment]
@cowboysdude to each their own! This project is just an example of how you can make some cool things with the cognitive services API + some inexpensive hardware. You could fork the demo to make your own version where an image is not required for authentication. Perhaps a sensor could detect motion and display the UI? Or use the speech recognition API?
